yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  "babel-preset-react-app@*":
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": "*"
  "eslint-config-react-app@*":
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  "jeanmomo@*":
    dependencies:
      "@testing-library/dom": "*"
      "eslint": "*"
  "react-dev-utils@*":
    dependencies:
      "typescript": "*"
      "webpack": "*"
  "react-scripts@*":
    dependencies:
      "autoprefixer": "*"
